{
 "title": "FastAPI Observability",
 "time": { "from": "2025-02-06T05:32:50.078Z", "to": "2025-02-06T07:02:53.458Z" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "app_name",
    "label": "Application Name",
    "query": {
     "query": "label_values(fastapi_app_info{}, app_name)"
    }
   },
   { "name": "log_keyword", "label": "Log Query" }
  ]
 },
 "panels": [
  {
   "title": "Tempo de requisição",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "http_request_duration_seconds_sum",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Acuracia",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "model_accuracy", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "model_performance_drift", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total de predições",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    { "expr": "model_total_predictions_total", "legendFormat": "__auto" }
   ]
  }
 ]
}